# Generated by Django 4.0.6 on 2022-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_alter_dish_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='imageUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
